# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c5d5e9aa7932b4d86ea07c986f7c406ec304abd483cc72aef8e591d97e7e3c512bc1680d7012954ab1ee008404b44e0ee94f200a5469716cba83ea46892e53

test:
  secret_key_base: 827b255307142ec28eb1261b499136927635710024f752a9cae9d72cb552ee6b667984e52d970cf18772507703e57a0c5bae9c94b4151a73eadab4e3bcb73d3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
